name: Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '*.md'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Write environment variables
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > ${{ github.workspace }}/.env.local
          echo "MONGO_DB=${{ secrets.MONGO_DB }}" >> ${{ github.workspace }}/.env.local
          echo "GC_API_KEY=${{ secrets.GC_API_KEY }}" >> ${{ github.workspace }}/.env.local

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: ${{ github.workspace }}
        run: pnpm run build

      - name: Restart app
        run: pm2 restart multimoco
